extends "res://tests/town_life_acceptance.gd"

func run() -> void:
	var path := "user://town-visitor-%d.json" % Time.get_ticks_usec()
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string(JSON.stringify(fixture(), "", true, true))
	file.close()
	var town := Town.new()
	check(town.load_from(path).ok, "visitor test fixture loads")
	check(not town.visitor_inquiry("fixture:a", "帮忙？", "ask-1", "scripted_player_fixture").ok, "visitor must have a host position")
	town.host_visitor_position(Vector3(8, 0, 0))
	check(not town.visitor_inquiry("fixture:a", "帮忙？", "ask-1", "scripted_player_fixture").ok, "remote visitor cannot be heard")
	town.host_visitor_position(Vector3(1, 0, 0))
	var resources: Dictionary = town.snapshot().survival.duplicate(true)
	var requested := town.transaction(path, func(): return town.visitor_inquiry("fixture:a", "有什么需要帮忙？", "ask-1", "scripted_player_fixture"))
	check(requested.ok, "nearby inquiry is durable")
	check(town.snapshot().residents.size() == 3, "visitor does not become a fabricated original resident")
	check(town.resident_view("fixture:a").experiences[-1].source == "scripted_player_fixture", "automated player action labelled honestly")
	check(town.resident_view("fixture:b").experiences.is_empty(), "other resident does not inherit inquiry")
	check(not town.reply_to_visitor("fixture:b", requested.request_id, "willing", "答复", "wrong-reply").ok, "only addressee can reply")
	check(not town.reply_to_visitor("fixture:a", requested.request_id, "accepted_contract", "答复", "invented-contract").ok, "availability is not a contract")
	check(town.transaction(path, func(): return town.reply_to_visitor("fixture:a", requested.request_id, "unavailable", "需要休息。", "reply-1")).ok, "voluntary refusal persists")
	check(town.snapshot().survival == resources, "conversation grants no inventory or energy")
	var before := FileAccess.get_file_as_bytes(path)
	var restored := Town.new()
	check(restored.load_from(path).ok, "visitor dialogue cold load")
	check(FileAccess.get_file_as_bytes(path) == before, "no cold rewriting")
	check(restored.resident_view("fixture:a").experiences.size() == 2, "inquiry and reply retained once")
	check(restored.reply_to_visitor("fixture:a", requested.request_id, "unavailable", "需要休息。", "reply-1").duplicate, "duplicate receipt does not require redelivery")
	check(not restored.reply_to_visitor("fixture:a", requested.request_id, "willing", "改口", "reply-2").ok, "no extra reply without a nearby visitor")
	check(not restored.visitor_inquiry("fixture:a", "帮忙？", "forged", "opengameagent_live").ok, "resident model cannot impersonate player provenance")
	town.release_writer(path)
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	print(JSON.stringify({"suite": "town_visitor", "checks": checks, "failures": failures, "paid_calls": 0}))
	quit(0 if failures == 0 else 1)
